### ISSUE TITLE
Improve acceptance tests coverage

### ISSUE THREAD

**Issue by grzuy** [kickstarter/rack-attack#293]
Continue what started in https://github.com/kickstarter/rack-attack/pull/269, by writing more test cases that make assertions specifically about the behavior the user should expect the gem to provide to them, without any assertions about the internals or implementation details.

> [...] testing with respect to user needs, requirements [...] conducted to determine whether a system satisfies the acceptance criteria.
>
> from https://en.wikipedia.org/wiki/Acceptance_testing

---

User-facing features:

* [x] blocklist (#269)
* [x] safelist (#269)
* [x] throttle (#269)
* [x] allow2ban (#304)
* [x] fail2ban (#303)
* [x] tracks (#294)
* [x] custom throttled response (#298)
* [x] custom blocked response (#298)
* [x] cache store config for throttle (#297)
* [x] cache store config for allow2ban (#305)
* [x] cache store config for fail2ban (#305)
* [x] cache store config when Rails present (#307)
* [x] throttle's Retry-After HTTP response header (#306)
* [x] throttle's limit argument as a proc (#309)
* [x] throttle's period argument as a proc (#309)
* [x] ability to extend request object (#310)
* [x] blocklisted_response access to match data (#311)
* [x] throttled_response access to match_data (#311)
* [x] notifications (#319)
