### ISSUE TITLE
Provide more clarity on when/how the cache store needs to be configured

### ISSUE THREAD

**Issue by grzuy** [kickstarter/rack-attack#300]
Try to avoid, as much as possible, any confusion from users about when and how they need to configure the cache store

* How it defaults depending on Rails presence
* When it is needed
* What type of cache store is suitable, needs to respond to which methods, etc
---

* [x] Give clearer error message in case using throttle but cache store is not set (https://github.com/kickstarter/rack-attack/pull/274)
* [x] Give clearer error message in case using throttle but cache store is set but incompatible (https://github.com/kickstarter/rack-attack/pull/274)
* [x] Give clearer error message in case using fail2ban but cache store is not set (#315)
* [x] Give clearer error message in case using fail2ban but cache store is set but incompatible (#315)
* [x] Give clearer error message in case using allow2ban but cache store is not set (#315)
* [x] Give clearer error message in case using allow2ban but cache store is set but incompatible (#315)
