### ISSUE TITLE
Shorthands for common block/safelist use cases

### ISSUE THREAD

**Issue by grzuy** [kickstarter/rack-attack#317]
As a rack-attack user
I want to have the ability to express common uses cases with less code
So that my rack-attack config is more concise
And easier to understand
And a bit less prone to error

---

* [x] `Rack::Attack.blocklist_ip("1.2.3.4")` (#320)
* [x] `Rack::Attack.blocklist_ip("1.2.0.0/16")` (#320)
* [x] `Rack::Attack.safelist_ip("1.2.3.4")` (#320)
* [x] `Rack::Attack.safelist_ip("1.2.0.0/16")` (#320)

---

Related:

* https://github.com/kickstarter/rack-attack/issues/98
* https://github.com/kickstarter/rack-attack/issues/140#issuecomment-132413167
* https://github.com/kickstarter/rack-attack/issues/143#issuecomment-154226777
